# Generated by Django 6.1.1 on 2026-10-03 07:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='test/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('tech', models.CharField(choices=[('PY', 'PYTHON'), ('JS', 'JAVASCRIPT'), ('RD', 'REDIS')], max_length=2)),
            ],
        ),
    ]
