# Generated by Django 6.1.1 on 2026-10-03 09:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')])),
                ('date_reviewed', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='myApp.firstmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileExpansion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_url', models.URLField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('first_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expansion', to='myApp.firstmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('first_models', models.ManyToManyField(related_name='stores', to='myApp.firstmodel')),
            ],
        ),
    ]
